services:
  - type: web
    name: linebot-gemini-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=$PORT
    plan: free

  - type: worker
    name: linebot-gemini-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    plan: free
